networkmanger: meta-oe world build failes
ERROR: Nothing RPROVIDES 'dnsmasq' (but /home/akuster/oss/clean/meta-openembedded/meta-oe/recipes-connectivity/networkmanager/networkmanager_0.9.8.10.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'dnsmasq' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dnsmasq']
ERROR: Required build target 'networkmanager' has no buildable providers.
Missing or unbuildable dependency chain was: ['networkmanager', 'dnsmasq']

move networkmanager from meta-oe to meta-networking.

Signed-off-by: Armin Kuster <akuster808@gmail.com>